# Generated by Django 5.0.6 on 2024-07-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='video_url',
            new_name='youtube_link',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='grade_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
