# Generated by Django 5.0.6 on 2024-07-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Official',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
